# Generated by Django 5.1.7 on 2025-03-26 01:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='confirm',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='employer',
            name='password',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
