# Generated by Django 5.1.7 on 2025-04-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user_delete_employer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
