# Generated by Django 5.2 on 2025-04-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='photos/25/04/13/Job_seeking.png', upload_to='photos/%y/%m/%d'),
        ),
    ]
