# Generated by Django 5.1.6 on 2025-04-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Emp_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('paid_internship', 'Paid Internship'), ('unpaid_internship', 'Unpaid Internship')], default='full_time', max_length=20),
        ),
    ]
