# Generated by Django 5.1.6 on 2025-04-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_job_emp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Deadline_of_application',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='period',
            field=models.CharField(blank=True, default='', help_text='e.g. 6 months, 1 year', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salaryoffer',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
