# Generated by Django 5.1.6 on 2025-04-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_job_deadline_of_application_alter_job_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Deadline_of_application',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
