# Generated by Django 5.1.6 on 2025-04-18 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_job_deadline_of_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Deadline_of_application',
            field=models.DateTimeField(),
        ),
    ]
