# Generated by Django 5.2 on 2025-04-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
