# Generated by Django 5.2 on 2025-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_delete_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='employer', max_length=20),
        ),
    ]
