# Generated by Django 5.2 on 2025-04-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_profile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vision',
            field=models.CharField(blank=True, default='', null=True),
        ),
    ]
