# Generated by Django 5.2 on 2025-05-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_remove_profile_user_type_profile_business_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='employer', max_length=20),
        ),
    ]
