# Generated by Django 5.2 on 2025-04-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(default='jobseeker', max_length=20),
        ),
    ]
