# Generated by Django 5.2 on 2025-05-02 12:23

import jobseeker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_jobapplication_portfolio_link_jobapplication_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, default='Profiles/68/photos/default.png', null=True, upload_to=jobseeker.models.user_photo_path),
        ),
    ]
